power <- read.table("household_power_consumption.txt", sep=";", na.strings="?", colClasses=c("character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"), header = T)
power$newtime <- paste(power$Date, power$Time, sep=" ")
power$newtime <- strptime(power$newtime, "%d/%m/%Y %H:%M:%S")
Relevant <- subset(power, Date=="1/2/2007" | Date=="2/2/2007")
png(file="plot1.png")
hist(Relevant$Global_active_power, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()
