power <- read.table("household_power_consumption.txt", sep=";", na.strings="?", colClasses=c("character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"), header = T)
power$newtime <- paste(power$Date, power$Time, sep=" ")
power$newtime <- strptime(power$newtime, "%d/%m/%Y %H:%M:%S")
Relevant <- subset(power, Date=="1/2/2007" | Date=="2/2/2007")
png(file="plot3.png")
plot(Relevant$newtime, Relevant$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(Relevant$newtime, Relevant$Sub_metering_2, type="l", xlab="", ylab="Energy sub metering", col="red")
lines(Relevant$newtime, Relevant$Sub_metering_3, type="l", xlab="", ylab="Energy sub metering", col="blue")
legend("topright", lty=1, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()